import type { User, Authority, Officer, Category, Complaint, ComplaintStatusEvent, Note, NotificationItem } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-cit-1',
    email: 'citizen@aquaguard.gov.in',
    name: 'Aarav Patel',
    role: 'Citizen',
    phone: '+91 98765 43210',
    accountStatus: 'active',
    createdAt: '2026-01-15T08:30:00Z',
  },
  {
    id: 'user-auth-1',
    email: 'authority@aquaguard.gov.in',
    name: 'Metropolis Water Board Director',
    role: 'Authority',
    phone: '+91 98765 11111',
    accountStatus: 'active',
    createdAt: '2026-01-01T10:00:00Z',
  },
  {
    id: 'user-off-1',
    email: 'officer@aquaguard.gov.in',
    name: 'Officer Rajesh Kumar',
    role: 'Field Officer',
    phone: '+91 98765 22222',
    accountStatus: 'active',
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'user-adm-1',
    email: 'admin@aquaguard.gov.in',
    name: 'System Admin Security Team',
    role: 'Admin',
    phone: '+91 98765 00000',
    accountStatus: 'active',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const MOCK_AUTHORITIES: Authority[] = [
  {
    id: 'auth-1',
    name: 'Central Zone Utility Board',
    jurisdictionArea: 'Ward 1 - Ward 15',
    contactEmail: 'central.board@aquaguard.gov.in',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'auth-2',
    name: 'Northern Coastal Water Department',
    jurisdictionArea: 'Ward 16 - Ward 30',
    contactEmail: 'north.board@aquaguard.gov.in',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const MOCK_OFFICERS: Officer[] = [
  {
    id: 'off-1',
    userId: 'user-off-1',
    authorityId: 'auth-1',
    userName: 'Officer Rajesh Kumar',
    userEmail: 'officer@aquaguard.gov.in',
    area: 'Ward 14 (Industrial Corridor)',
    status: 'on_field',
    currentWorkload: 3,
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'off-2',
    userId: 'user-off-2',
    authorityId: 'auth-1',
    userName: 'Technician Priya Sharma',
    userEmail: 'priya.sharma@aquaguard.gov.in',
    area: 'Ward 8 (Residential North)',
    status: 'available',
    currentWorkload: 1,
    createdAt: '2026-01-12T09:00:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Water Shortage', description: 'Severe interruption or non-supply of municipal water', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'cat-2', name: 'Pipeline Leakage', description: 'Main line burst, feeder pipe leaking, water wastage', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'cat-3', name: 'Contaminated Water', description: 'Discolored, turbid, foul smelling, or unsafe supply', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'cat-4', name: 'Low Pressure', description: 'Inadequate flow rate to multi-story buildings', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'cat-5', name: 'Meter Defect', description: 'Faulty reading, damaged, or tampered billing meter', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'cat-6', name: 'Unauthorized Connection', description: 'Illegal tapping of municipal water mains', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'cat-7', name: 'Infrastructure Damage', description: 'Valves, pump house, or storage reservoir failure', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'cat-8', name: 'Billing Query', description: 'Discrepancy in water tariff or consumption charges', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'cat-9', name: 'Other Issue', description: 'General water utility complaint', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-101',
    complaintCode: 'AQ-2026-001245',
    citizenId: 'user-cit-1',
    citizenName: 'Aarav Patel',
    citizenPhone: '+91 98765 43210',
    categoryId: 'cat-2',
    categoryName: 'Pipeline Leakage',
    severity: 'Critical',
    status: 'In Progress',
    address: 'Near Cross Road 4, Sector 7, Ward 14',
    latitude: 19.0760,
    longitude: 72.8777,
    city: 'Metropolis',
    state: 'State Central',
    pincode: '400012',
    description: 'Major underground pipeline rupture flooding main thoroughfare. Severe water pressure loss across Sector 7.',
    authorityId: 'auth-1',
    authorityName: 'Central Zone Utility Board',
    assignedOfficerId: 'off-1',
    assignedOfficerName: 'Officer Rajesh Kumar',
    createdAt: '2026-02-28T09:15:00Z',
    updatedAt: '2026-02-28T11:30:00Z',
  },
  {
    id: 'cmp-102',
    complaintCode: 'AQ-2026-001246',
    citizenId: 'user-cit-1',
    citizenName: 'Aarav Patel',
    citizenPhone: '+91 98765 43210',
    categoryId: 'cat-3',
    categoryName: 'Contaminated Water',
    severity: 'High',
    status: 'Submitted',
    address: 'Building 12B, Green Park Enclave, Ward 8',
    latitude: 19.0800,
    longitude: 72.8800,
    city: 'Metropolis',
    state: 'State Central',
    pincode: '400014',
    description: 'Muddy, discolored tap water reported across entire housing society since morning distribution shift.',
    authorityId: 'auth-1',
    authorityName: 'Central Zone Utility Board',
    createdAt: '2026-03-01T07:45:00Z',
    updatedAt: '2026-03-01T07:45:00Z',
  },
  {
    id: 'cmp-103',
    complaintCode: 'AQ-2026-001247',
    citizenId: 'user-cit-2',
    citizenName: 'Sneha Gupta',
    citizenPhone: '+91 98111 22233',
    categoryId: 'cat-1',
    categoryName: 'Water Shortage',
    severity: 'Medium',
    status: 'Resolved',
    address: 'Plot 45, Industrial Estate, Ward 14',
    city: 'Metropolis',
    state: 'State Central',
    pincode: '400012',
    description: 'No supply received during morning scheduled hours (06:00 to 09:00).',
    authorityId: 'auth-1',
    authorityName: 'Central Zone Utility Board',
    assignedOfficerId: 'off-1',
    assignedOfficerName: 'Officer Rajesh Kumar',
    createdAt: '2026-02-25T10:00:00Z',
    updatedAt: '2026-02-26T16:20:00Z',
  },
];

export const INITIAL_STATUS_EVENTS: ComplaintStatusEvent[] = [
  {
    id: 'evt-1',
    complaintId: 'cmp-101',
    fromStatus: null,
    toStatus: 'Submitted',
    changedById: 'user-cit-1',
    changedByName: 'Aarav Patel (Citizen)',
    changedRole: 'Citizen',
    reasonNotes: 'Complaint logged via citizen web portal.',
    createdAt: '2026-02-28T09:15:00Z',
  },
  {
    id: 'evt-2',
    complaintId: 'cmp-101',
    fromStatus: 'Submitted',
    toStatus: 'Acknowledged',
    changedById: 'user-auth-1',
    changedByName: 'Central Water Board Admin',
    changedRole: 'Authority',
    reasonNotes: 'Ticket verified by ward desk dispatcher.',
    createdAt: '2026-02-28T09:40:00Z',
  },
  {
    id: 'evt-3',
    complaintId: 'cmp-101',
    fromStatus: 'Acknowledged',
    toStatus: 'Assigned',
    changedById: 'user-auth-1',
    changedByName: 'Central Water Board Admin',
    changedRole: 'Authority',
    reasonNotes: 'Dispatched Senior Technician Officer Rajesh Kumar.',
    createdAt: '2026-02-28T10:05:00Z',
  },
  {
    id: 'evt-4',
    complaintId: 'cmp-101',
    fromStatus: 'Assigned',
    toStatus: 'In Progress',
    changedById: 'user-off-1',
    changedByName: 'Officer Rajesh Kumar',
    changedRole: 'Field Officer',
    reasonNotes: 'Arrived at site. Main isolation valve closed. Excavation started.',
    createdAt: '2026-02-28T11:30:00Z',
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'note-1',
    complaintId: 'cmp-101',
    authorId: 'user-off-1',
    authorName: 'Officer Rajesh Kumar',
    authorRole: 'Field Officer',
    noteText: 'Inspected 500mm feeder pipe. Heavy leak at joint 14B. Repair crew dispatched with replacement coupling.',
    isInternal: false,
    createdAt: '2026-02-28T11:35:00Z',
  },
  {
    id: 'note-2',
    complaintId: 'cmp-101',
    authorId: 'user-auth-1',
    authorName: 'Central Water Board Admin',
    authorRole: 'Authority',
    noteText: 'Traffic police notified regarding lane restriction near Sector 7 junction.',
    isInternal: true,
    createdAt: '2026-02-28T11:50:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-cit-1',
    title: 'Technician Assigned',
    message: 'Officer Rajesh Kumar has been dispatched to ticket AQ-2026-001245.',
    type: 'status_change',
    isRead: false,
    createdAt: '2026-02-28T10:05:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-cit-1',
    title: 'Work In Progress',
    message: 'Repair work commenced at Sector 7 junction.',
    type: 'status_change',
    isRead: false,
    createdAt: '2026-02-28T11:30:00Z',
  },
];
